apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  labels:
    run: minecraft-server
spec:
  ports:
  - protocol: TCP
    targetPort: 25565
    port: 25565
  selector:
    run: minecraft-server
  type: LoadBalancer
